apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: voice-agent
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http-metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
