---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: voice-agent-secrets
  namespace: voice-agent
spec:
  encryptedData:
    GROQ_API_KEY: AgBJLE9SrsCVEpKsk8rJShg2JEulk4FFiQwMLqm14KGpjiCTvRLcpVyUrQ6DCBOGS//p7nJeZnMOGcS2m4zoYm8TrVlfenicLcHviXV1fpnppZKH+YfyLy7MJ06gtOC5eXVq8jXS6SGQNWFDr8hstLX+YGCR2j3O4XMAGx3oWTuJQ+1AqwYtue9XJhu2AniczL+8Phskl65JoJ+wn0pSmVAv1j/LZY17ucX1JmMvSPYUB76PkOYrYwXdmIUjM5rdu+zWobGN5m6wupg2nb+3idy07XcvTnmKsLMjPB0UW+8kTe7hVHs4EbpSWxSXZOZz6CrmrfSXBfDZ1WoE7Nj1Ae3qT6XXJF7xoWcdf4nrAWt0Y6wjnd/x3oyRZAtfz5Mk6FGb9/DrwzYeNnPH88qSwKl2ATbBuPSK0Wg0Y4aZgx+FFyLezbmELrhFtWTfBYvE/6dnkqdMBvhwfY37+5cIoNCP4pf9S0uVyWIJn77EcJcofhQnUrz1hC4oWv7KXQhREhofT9L6abgZsjlqiXwoUZNMhWUyack/9c/KCJQyo2iNnWr8m00wFfMTsyoq5b4gTTlfAz2m5rzkAKFupmYTCPuBYF9KFXpzthPdUEkexYxhs9dW569PAx3dZkZcpCVFBn+n/SzOP1QRe1KuZTkYiW2qosXPkMB+DcxH3MoEsV3CXkkai7KKjxeOIe6E2JOUEKcKuFegSYEkY3ohW3YKbTSUrvR57wHzA2H028kcOqPnUFDrN6knjf7I1P98Yo8nG53/AQ16QTaJSQ==
  template:
    metadata:
      name: voice-agent-secrets
      namespace: voice-agent
