---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: voice-agent-secrets
  namespace: voice-agent
spec:
  encryptedData:
    GROQ_API_KEY: AgCDjE4Aj+ts2FqHTq7JE002X2swOsDBBJt/cKCZznXzjKouSu0gcRUcqU/rV7OL8ZlnM7Uo168eBJWWQX6jlLmZxz5fLSIL56z75J70G3GfsfR2/BrOtwlgZ4VKEkj4fgXo3YCQE6ZOXZY2YZuQvpBfRkJaxe2OvOsH3JujbLmcpAPseFF3PblVhIRRjn5dB6UHOCCs2+V0LL6G+bT+lAurebBVa4xOsgj7KopiF5P50XI5fccAEiLhFihUVDIUKblozEqKKQwCTiGttAo62dU916rE0cWRGjA+6tHtlHpVkF5Htoe/6ZJ414P7uDkMw0fsfa+bpxG3r9YkeLrBhD34vuBLZ88IgW+mUSLTaOHgiNWN9/S3e7sXPaT/kp6Tu9cHjxQcArhvmSA1VAHagLkeMJC80mhXfWMZG4Wck70Zqbz2HuJzrjZVif6pku3QxO5pJsTGWoOifnxByx3tnu21LJ+k7JjzyCWoUZBNt2wWopdN0BYeZ57LI4Id8jOVSXBbJLGj768I/F6WL6zFySAlMhPXQb7LKgrIHX7iZihFFmTAcgakG4EFPizCVa31iMjidtaV1SaZvzcIFhihPR1ywKyjlXB8UFMOFBk1+PXZhlJ6y5iSxy2txcmVaDgaYragzGJhkmabjHUgZSRzqk79ul9lLlCgtT6buVLFy63pqHjbXexABOKMmPfLFDRN0pBtc/6dLfwLLmQCc5DdRkE/P9Pe6xDJz2l6D6vNOuuezsr9SanM11Vy6TfK3VZxOZzqXYR/ek1MTQ==
  template:
    metadata:
      name: voice-agent-secrets
      namespace: voice-agent
